# Generated by Django 4.2 on 2024-03-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Имейл")),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CircularSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="начало")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="окончание"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("Д", "daily"), ("Н", "weekly"), ("М", "monthly")],
                        default="Д",
                        max_length=2,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "created"),
                            ("Запущена", "in-progress"),
                            ("Завершена", "completed"),
                            ("Отменена", "cancelled"),
                        ],
                        default="Создана",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        to="distribution.client", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметры рассылки",
                "verbose_name_plural": "Параметры рассылки",
                "ordering": ["start_date", "frequency"],
            },
        ),
    ]
