# Generated by Django 4.2 on 2024-03-25 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("distribution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="circularsettings",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="distribution.message",
                verbose_name="сообщение",
            ),
        ),
        migrations.AddField(
            model_name="circularsettings",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер рассылки",
            ),
        ),
    ]
