# Generated by Django 4.2 on 2024-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0004_client_owner_message_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="circularsettings",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
